import { PortfolioItem } from "@/types/portfolio";

export const portfolioItems: PortfolioItem[] = [
  {
    id: "item-01",
    type: "image",
    category: "Calendar Management",
    title: "Calendar Setup (After)",
    description: "Streamlined, color-coded calendar organized by priority, focus block time, and meeting slots.",
    cloudinaryId: "maygift-glory/Calendar Management/after_calendar_management",
    aspectRatio: "16/9",
    featured: true,
  },
  {
    id: "item-02",
    type: "image",
    category: "Calendar Management",
    title: "Calendar Setup (Before)",
    description: "Initial cluttered calendar view before restructuring and prioritizing events.",
    cloudinaryId: "maygift-glory/Calendar Management/before_calendar_management",
    aspectRatio: "1/1",
  },
  {
    id: "item-03",
    type: "video",
    category: "Calendar Management",
    title: "Calendar Reorganization Walkthrough",
    description: "Screen recording showing how meeting booking options were integrated to eliminate scheduling back-and-forth.",
    cloudinaryId: "maygift-glory/Calendar Management/After Video Calendar Management",
    aspectRatio: "16/9",
    duration: "0:15",
  },
  {
    id: "item-04",
    type: "video",
    category: "Calendar Management",
    title: "Prior Restructuring Audit",
    description: "Detailed run-through of schedule overlaps, double-bookings, and priority issues before cleaning.",
    cloudinaryId: "maygift-glory/Calendar Management/Before Calendar Management",
    aspectRatio: "4/3",
    duration: "0:10",
  },
  {
    id: "item-05",
    type: "video",
    category: "Inbox Management",
    title: "Gmail Inbox-Management & triage flow",
    description: "A complete triage workflow demonstration showcasing advanced filtering, labeling, and prioritization.",
    cloudinaryId: "maygift-glory/Inbox Management/Inbox-Management",
    aspectRatio: "16/9",
    duration: "0:48",
  },
  {
    id: "item-06",
    type: "video",
    category: "Travel Management",
    title: "Travel Coordination & Logistics Briefing",
    description: "Detailed walkthrough of building structured multi-city flight, lodging, transit, and agenda itineraries.",
    cloudinaryId: "maygift-glory/Travel Management/Travel_Management_and_coordination_hforsb",
    aspectRatio: "4/3",
    duration: "0:54",
  },
  {
    id: "item-07",
    type: "video",
    category: "Expense Report",
    title: "Expense Auditing & Receipts Logging",
    description: "Demonstrating automated transaction sorting, invoice matching, and generating monthly summaries for review.",
    cloudinaryId: "maygift-glory/Expense Report/expense_report_s5blkm",
    aspectRatio: "1/1",
    duration: "0:35",
  },
  {
    id: "item-08",
    type: "image",
    category: "Calendar Management",
    title: "Secondary Color-Coding Setup",
    description: "Detailed categorization scheme showing focus periods, executive lunches, and board prep hours.",
    cloudinaryId: "maygift-glory/Calendar Management/after_calendar_management_2",
    aspectRatio: "4/3",
  },
];
